### ISSUE TITLE
CSRF bug in old AXIOS lib

### ISSUE THREAD

**Issue by Xotabu4** [AgoraIO/agora-rtc-web#3]
### AgoraRTC SDK version

latest

### Fail Rate

100%

### Link to minimal reproduction

https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459

### Steps to reproduce

https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459

### What is expected?

No security issues

### What is actually happening?

security issue

**Comment by simo-an** [comment]
This issue was submit here: https://github.com/axios/axios/issues/6022
agora-rtc-sdk-ng is using axios@0.27.2 which is not included in the vulnerability versions.

![17001147411912](https://github.com/AgoraIO/agora-rtc-web/assets/38021707/31c597f0-1ee5-4c5b-bf25-989e2a501ed1)


So there is no related security issus.

We also consider to upgrade axios to latest version at next version

**Comment by simo-an** [comment]
we have upgrade axios's version to 1.6.7 at agora-rtc-sdk-ng@4.20.2
